name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# Ustawienie domyślnych uprawnień dla całego workflow w celu zwiększenia bezpieczeństwa
permissions:
  contents: read

jobs:
  build_android:
    runs-on: ubuntu-latest
    # Dodanie limitu czasu, aby uniknąć "wiszenia" akcji i niepotrzebnego zużycia zasobów
    timeout-minutes: 15
    steps:
      # Wersja v4 jest najnowszą i najbezpieczniejszą wersją
      - name: Checkout repository
        uses: actions/checkout@v4

      # Wersja v4 z wbudowanym cache dla menedżera pakietów (yarn)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # Zalecana nowsza wersja LTS Node.js
          cache: 'yarn'
          cache-dependency-path: telon-gateway-app/yarn.lock

      - name: Install Node.js dependencies
        working-directory: ./telon-gateway-app
        run: yarn install

      # Wersja v4 jest najnowsza i najszybsza
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          # Wbudowane cache dla Gradle, prostsze i bardziej niezawodne
          cache: gradle

      - name: Grant execute permission for gradlew
        working-directory: ./telon-gateway-app/android
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./telon-gateway-app/android
        run: ./gradlew assembleDebug

      # Wersja v4 jest najnowsza, zalecana przez GitHub
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: telon-gateway-app/android/app/build/outputs/apk/debug/app-debug.apk
